# Site settings
title: Graduate Student Association of Neuroscience at McGill University
brand: GSAN archives
email: gsan.mcgill@gmail.com
description: We are the Graduate Student Association of Neuroscience at McGill University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "/"
copyright: © GSAN

# Build settings
markdown: kramdown

# The video that plays.
video: "u7deClndzQw"

# The navigation.
navigation:
  left:
    links:
      - title: About Us
        dropdown:
          - title: Home
            href: /about-us/
          - title: 2014-15 Executive Members
            href: /about-us/gsan-executive-2014-2015
          - title: Constitution
            href: /about-us/constitution/
          - title: Finance
            href: /about-us/finance/
          - title: Contact Us
            href: /about-us/current-committee-members/
          - title: Past GSAN Committee
            href: /about-us/past-committee-members/
      - title: Academic
        dropdown:
          - title: Home
            href: /academic/
          - title: Research Symposium
            href: /academic/research-symposium/
          - title: French Classes
            href: /academic/french-classes/
      - title: Social
        dropdown:
          - title: Home
            href: /social/
          - title: Photos of Past Events
            href: /social/gallery/
      - title: Athletics
        href: /athletics/
      - title: New and International
        dropdown:
          - title: Home
            href: /new-intl/
          - title: Welcome
            href: /new-intl/welcome/
          - title: Buddy Program
            href: /new-intl/buddy-program/
      - title: NeuroArt
        href: /neuroart/
      - title: Blog
        dropdown:
          - title: Home
            href: /blog/
          - title: About the Blog
            href: /blog/about-blog/
          - title: Submit
            href: /blog/submit/
      - title: Peer Support
        dropdown:
          - title: Home
            href: /peers/
          - title: Ask for Help
            href: /peers/ask-for-help/
          - title: Support Resources
            href: /peers/support-resources/
          - title: Join the PST
            href: /peers/join/
      - title: Back to GSAN
        href: http://axon.gsaneuro.com


#  right:
#    content: nav/right.html

# The footer section.
footer:
  sections:
    - title: Student Services
      links:
        - href: mcgill.ca/skillsets
          title: SKILLSETS
        - href: mcgill.ca/caps
          title: Career Planning Service (CaPS)
        - href: https://www.msn.com
          title: MSN
    - title: Social Media
      links:
        - href: twitter.com/McGill_IPN
          title: IPN on Twitter
        - href: twitter.com/GSANMcGill
          title: GSAN on Twitter
        - href: facebook.com/pages/McGill-University-Integrated-Program-in-Neuroscience/271029572921909
          title: IPN on Facebook
        - href: facebook.com/NeuroMontreal/
          title: MNI on Facebook

    - title: Neuroscience Socieities
      links:
        - href: braincanada.ca
          title: Brain Canada
        - href: www.can-acn.org
          title: Canadian Association for Neuroscience
        - href: neuroinflammation.com
          title: CIHR- Neuroinflammation Training Program
  company_info:
    title: GSAN at McGill
    name: IPN
    website: http://www.gsaneuro.com
    phone: 555-123-4567
    address:
      street: 123 Main St.
      city: Montreal
      state: QC
      zip: H2X
