# Site settings
title: Graduate Student Association of Neuroscience at McGill University
brand: GSAN archives
email: gsan.mcgill@gmail.com
description: We are the Graduate Student Association of Neuroscience at McGill University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "archive.gsaneuro.com"
copyright: © GSAN

# Build settings
markdown: kramdown

# The video that plays.
video: "u7deClndzQw"

# The navigation.
navigation:
  left:
    links:
      - title: About Us
        dropdown:
          - title: Home
            href: tau/about-us/
          - title: 2014-15 Executive Members
            href: tau/about-us/gsan-executive-2014-2015
          - title: Constitution
            href: tau/about-us/constitution/
          - title: Finance
            href: tau/about-us/finance/
          - title: Contact Us
            href: tau/about-us/current-committee-members/
          - title: Past GSAN Committee
            href: tau/about-us/past-committee-members/
      - title: Academic
        dropdown:
          - title: Home
            href: tau/academic/
          - title: Research Symposium
            href: tau/academic/research-symposium/
          - title: French Classes
            href: tau/academic/french-classes/
      - title: Social
        dropdown:
          - title: Home
            href: tau/social/
          - title: Photos of Past Events
            href: tau/social/gallery/
      - title: Athletics
        href: tau/athletics/
      - title: New and International
        dropdown:
          - title: Home
            href: tau/new-intl/
          - title: Welcome
            href: tau/new-intl/welcome/
          - title: Buddy Program
            href: tau/new-intl/buddy-program/
      - title: NeuroArt
        href: tau/neuroart/
      - title: Blog
        dropdown:
          - title: Home
            href: tau/blog/
          - title: About the Blog
            href: tau/blog/about-blog/
          - title: Submit
            href: tau/blog/submit/
      - title: Peer Support
        dropdown:
          - title: Home
            href: tau/peers/
          - title: Ask for Help
            href: tau/peers/ask-for-help/
          - title: Support Resources
            href: tau/peers/support-resources/
          - title: Join the PST
            href: tau/peers/join/
      - title: Back to GSAN
        href: http://axon.gsaneuro.com


#  right:
#    content: nav/right.html

# The footer section.
footer:
  sections:
    - title: Useful Links 1
      links:
        - href: https://www.google.com
          title: Google.com
        - href: https://www.yahoo.com
          title: Yahoo.com
        - href: https://www.msn.com
          title: MSN
    - title: Useful Links 2
      links:
        - href: https://www.google.com
          title: Google.com
        - href: https://www.yahoo.com
          title: Yahoo.com
        - href: https://www.msn.com
          title: MSN
    - title: Useful Links 3
      links:
        - href: https://www.google.com
          title: Google.com
        - href: https://www.yahoo.com
          title: Yahoo.com
        - href: https://www.msn.com
          title: MSN
  company_info:
    title: Our office
    name: Company Name
    website: http://companysite.com
    phone: 555-123-4567
    address:
      street: 123 Main St.
      city: Dallas
      state: TX
      zip: 75001
